### ISSUE TITLE
Sorting the list of orders has no effect

### ISSUE THREAD

**Issue by leganz** [jonassiewertsen/statamic-butik#158]
It seems that sorting by "created_at" has no effect...

![Bildschirmfoto 2020-12-14 um 17 16 01](https://user-images.githubusercontent.com/3373530/102105922-414f4b00-3e30-11eb-9e2e-2817459c1d0d.png)
![Bildschirmfoto 2020-12-14 um 17 15 58](https://user-images.githubusercontent.com/3373530/102105931-41e7e180-3e30-11eb-800e-c06d148838a0.png)

**Comment by leganz** [comment]
ok i think i need to specify => sorting at all doesn't work right now - now console messages or so.

**Comment by jonassiewertsen** [comment]
Thanks for the heads up. 

This will be fixed with the rewritten search integration:
https://github.com/jonassiewertsen/statamic-butik/issues/127

If you want, you can follow up on the branch existing for it:
https://github.com/jonassiewertsen/statamic-butik/tree/order-search

The proof of concept has already been finished and will hopefully be integrated soon.
