### ISSUE TITLE
Parse category data into category view

### ISSUE THREAD

**Issue by dwainscheeren** [jonassiewertsen/statamic-butik#159]
It would be handy to put the category data into the category view to handle them in the view file. This way you can use the category name in the view for example

**Comment by jonassiewertsen** [comment]
We need a better solution for sure! I won't focus on this feature right now, because there will be a big change on how categories will work.

In the future those categories will be removed and replaced with a native Statamic option. Instead of categories as build into the core of butik, you can create a collection as categories or even taxonomies. Just as you prefer. 

Please follow this discussion or participate in it to shape the future category functionality: https://github.com/jonassiewertsen/statamic-butik/discussions/175
