### ISSUE TITLE
Can not change slug of category

### ISSUE THREAD

**Issue by freshface** [jonassiewertsen/statamic-butik#187]
## Describe the bug

if i change the slug of a category the category cannot be updated.

## How to reproduce

1. add a category to a product
2. edit it
3. change the slug
4. try to save it

## Expected behavior
To save the category

## Environment

Latest version of statamic and butik

**Comment by jonassiewertsen** [comment]
You can change the name and slug, if the category is not connected to any product. 

If the category already has been connected to a product, you can't change the slug. This is related to the foreign key constraints to make sure nothing breaks. I can see that is not 100% ideal from a UI perspectiveve, but actually is expected behavior. 

I will close this issue for now, in favor of how categories will work with butik version 4.0. 

Please comment here if this is a bigger problem than I do anticipate.
