### ISSUE TITLE
PaymentGateway stub arguments do not match

### ISSUE THREAD

**Issue by rrelmy** [jonassiewertsen/statamic-butik#226]
## Describe the bug
https://github.com/jonassiewertsen/statamic-butik/blob/e5ff7a9d0ad2a6c1485deafbebcfdb4797e645e8/src/Commands/stubs/PaymentGateway.php.stub#L35

There is a `$shippings` variable passed to the `createOrder` method which does not exist

---

Additionally it would be nice to provide an interface/sample how `Payment` should look like

---

And a note in the documentation that `butik:gateway` expects an name
https://www.butik.dev/extending/payment-gateway

## How to reproduce
1. `php please butik:gateway Sample`
2. Check generated code

## Expected behavior
Stub code should call method correctly

## Environment

Statamic 3.0.49 Pro
Laravel 8.41.0
PHP 7.4.16
jonassiewertsen/statamic-butik 3.5.5
jonassiewertsen/statamic-livewire 2.5.0

**Comment by jonassiewertsen** [comment]
You're right, there has been a mix-up with the variables passed into the order create method. Good catch. 

This has been fixed in the last release https://github.com/jonassiewertsen/statamic-butik/releases/tag/v3.5.6

Thanks for the tip about the documentation as well. An example name has been added.

It's pretty different on how to handle a Payment, so it's hard to give a general example. 
Maybe it might be helpful to see how the payment has been implemented with Mollie. 

This is the key element and only one example. I still hope it is helpful to you!
https://github.com/jonassiewertsen/statamic-butik/blob/master/src/Http/Controllers/PaymentGateways/MolliePaymentGateway.php#L31-L33

Please let me know if things still are unclear.
